image: "glimmertreasure/node:14.17.0"

build_for_production:
  stage: build
  tags:
    - blog-runner
  script:
    - pwd
    - ls
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./public
  only:
    - master

deploy_to_production:
  stage: deploy
  # before_script:
  #   - aws --version
  tags:
    - blog-runner
  script:
    - /app/ossutil64 rm oss://$BUCKET_NAME/ -r -f -a -e $ENDPOINT -i $ID -k $KEY
    - /app/ossutil64 sync ./public/ oss://$BUCKET_NAME/  --delete -e $ENDPOINT -i $ID -k $KEY
  dependencies:
    - build_for_production
  only:
    - master