image: "glimmertreasure/node:14.17.0"

build_for_production:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./public
  only:
    - production

deploy_to_production:
  stage: deploy
  # before_script:
  #   - aws --version
  script:
    - ./ossutil sync ./public/ oss://$BUCKET_NAME/  --delete -e $ENDPOINT -i $ID -k $KEY
    # - aws s3 sync ./public/ oss://$BUCKET_NAME/  --delete -e $ENDPOINT -i $ID -k $KEY
  dependencies:
    - build_for_production
  only:
    - production