name: blog-depoly

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - name: hexo build
        run: |
          npm install
          npm run clean
          npm run build
      - name: set ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{ secrets.ALI_OSS_ASSCESS_ID }}
          access-key-secret: ${{ secrets.ALI_OSS_ASSCESS_SECRET }}
      - name: copy to ali-oss
        run: ossutil cp public oss://blog-glimmertreasure-com.oss-cn-hangzhou.aliyuncs.com -rf
